### ISSUE TITLE
팀별 주제 선정하기

### ISSUE THREAD

**Issue by seongyoo** [Team18Project/Miniproject#1]

**Comment by seongyoo** [comment]
이름 삼행시 추천해주는 기능

**Comment by Kimjisue** [comment]
오석 상상랩 예약 기능

**Comment by seongyoo** [comment]
Todolist 같은 공부할 것을 저장하는 기능

**Comment by seongyoo** [comment]
계정 아이디와 비밀번호들을 저장해주는 기능(네이버라고 치면 그 사이트의 아이디와 비밀번호를 입력해두었던 것이 출력이 된다)

**Comment by Kimjisue** [comment]
독서 기록장이나 영화 기록 등 날짜와 분야별로 기록할 수 있는 기능

**Comment by Kimjisue** [comment]
1.  계정 아이디와 비밀번호들을 저장해주는 기능
2. 독서 기록장이나 영화 기록 등 날짜와 분야별로 기록할 수 있는 기능

**Comment by seongyoo** [comment]
2번이 추가기능 함수들을 많이 만들 수 있을 것 같습니다

**Comment by Kimjisue** [comment]
2. 독서 기록장이나 영화 기록 등 날짜와 분야별로 기록할 수 있는 기능
- 독서 기록 입력
- 영화 기록 입력 
- 독서 기록 출력
- 영화 기록 출력
- 날짜별로 출력
- 독서 기록 입력
- 영화 기록 입력 
- 읽고싶은 책 등록 
- 보고싶은 영화 등록

**Comment by seongyoo** [comment]
2번으로 결정
