### ISSUE TITLE
CRUD Mini project 를 진행할 주제 선정 및 역할 분담

### ISSUE THREAD

**Issue by Kimjisue** [Team18Project/Miniproject#2]

**Comment by Kimjisue** [comment]
주제 : 독서 기록장이나 영화 기록 등 날짜와 분야별로 기록할 수 있는 기능

**Comment by seongyoo** [comment]
드라마도 추가하면 좋을 것 같습니다

**Comment by seongyoo** [comment]
1. 책, 영화, 드라마를 기록하는 기능

**Comment by seongyoo** [comment]
1. 책, 영화, 드라마를 기록하는 기능
2. 기록한 리스트를 출력하는 기능

**Comment by seongyoo** [comment]
1. 책, 영화, 드라마를 기록하는 기능
2. 기록한 리스트를 출력하는 기능
3. 기록한 리스트를 수정하는 기능
4. 기록한 리스트를 삭제하는 기능
5. 데이터 파일 저장/읽어오는 기능

**Comment by Kimjisue** [comment]
1. 책, 영화, 드라마를 기록하는 기능
2. 기록한 리스트를 출력하는 기능
3. 기록한 리스트를 수정하는 기능
4. 기록한 리스트를 삭제하는 기능
5. 데이터 파일 저장/읽어오는 기능 
6. 책, 영화, 드라마 제목 검색 기능

**Comment by Kimjisue** [comment]
1. 책, 영화, 드라마를 기록하는 기능
2. 기록한 리스트를 출력하는 기능
3. 기록한 리스트를 수정하는 기능
4. 기록한 리스트를 삭제하는 기능
5. 데이터 파일 저장/읽어오는 기능
6. 책, 영화, 드라마 제목 검색 기능
7. 파일 저장 
8. 파일 읽어오기

**Comment by seongyoo** [comment]
책, 영화, 드라마를 기록하는 기능
기록한 리스트를 출력하는 기능
기록한 리스트를 수정하는 기능
기록한 리스트를 삭제하는 기능
데이터 파일 저장/읽어오는 기능
책, 영화, 드라마 제목 검색 기능
책, 영화, 드라마 장르 검색 기능

**Comment by seongyoo** [comment]
책, 영화, 드라마를 기록하는 기능
기록한 리스트를 출력하는 기능
기록한 리스트를 수정하는 기능
기록한 리스트를 삭제하는 기능
데이터 파일 저장/읽어오는 기능
책, 영화, 드라마 제목 검색 기능
책, 영화, 드라마 장르 검색 기능
책, 영화, 드라마 날짜 검색 기능
북마크 기능

**Comment by seongyoo** [comment]
책, 영화, 드라마를 기록하는 기능
기록한 리스트를 출력하는 기능
기록한 리스트를 수정하는 기능
기록한 리스트를 삭제하는 기능
데이터 파일 저장/읽어오는 기능
책, 영화, 드라마 제목 검색 기능
책, 영화, 드라마 장르 검색 기능
책, 영화, 드라마 날짜 검색 기능
북마크 기능
메뉴선택창

**Comment by seongyoo** [comment]
구조체 변수들 정하기

**Comment by seongyoo** [comment]
책, 영화, 드라마 제목 변수

**Comment by Kimjisue** [comment]
장르, 내용 변수

**Comment by seongyoo** [comment]
책, 영화, 드라마 제목 변수
장르, 내용, 날짜 변수

**Comment by Kimjisue** [comment]
책, 영화, 드라마 제목 변수
장르, 내용, 날짜 변수
북마크 변수, 메뉴 변수

**Comment by Kimjisue** [comment]
책, 영화, 드라마 제목 변수
장르, 내용, 날짜 변수
북마크 변수

**Comment by Kimjisue** [comment]
북마크 변수 
1. 1번 입력시 입력된 리스트에서 다시 보고싶은 책,영화,드라마 출력 
2. 2번 입력시 보고싶은 책,영화,드라마 출력

**Comment by Kimjisue** [comment]
북마크 함수 
1. 1번 입력시 입력된 리스트에서 다시 보고싶은 책,영화,드라마 출력
2. 2번 입력시 보고싶은 책,영화,드라마 출력

**Comment by Kimjisue** [comment]
<역할 분담>

**Comment by seongyoo** [comment]
1. 책, 영화, 드라마를 기록하는 기능
2. 기록한 리스트를 출력하는 기능
3. 기록한 리스트를 수정하는 기능
4. 기록한 리스트를 삭제하는 기능
5 .데이터 파일 저장/읽어오는 기능
6. 책, 영화, 드라마 제목 검색 기능
7. 책, 영화, 드라마 장르 검색 기능
8. 책, 영화, 드라마 날짜 검색 기능
9. 북마크 기능
10. 메뉴선택창

**Comment by Kimjisue** [comment]
> 1. 책, 영화, 드라마를 기록하는 기능
> 2. 기록한 리스트를 출력하는 기능
> 3. 기록한 리스트를 수정하는 기능
> 4. 기록한 리스트를 삭제하는 기능
> 5 .데이터 파일 저장/읽어오는 기능
> 6. 책, 영화, 드라마 제목 검색 기능
> 7. 책, 영화, 드라마 장르 검색 기능
> 8. 책, 영화, 드라마 날짜 검색 기능
> 9. 북마크 기능
> 10. 메뉴선택창

**Comment by seongyoo** [comment]
1. 메뉴선택창
2. 책, 영화, 드라마를 기록하는 기능
3. 기록한 리스트를 출력하는 기능
4. 기록한 리스트를 수정하는 기능
5. 기록한 리스트를 삭제하는 기능
6. 데이터 파일 저장/읽어오는 기능
7. 책, 영화, 드라마 제목 검색 기능
8. 책, 영화, 드라마 장르 검색 기능
9. 책, 영화, 드라마 날짜 검색 기능
10. 북마크 기능

**Comment by seongyoo** [comment]
1, 2, 3, 7, 8

**Comment by seongyoo** [comment]
4, 5, 6, 9, 10

**Comment by seongyoo** [comment]
제가 4, 5, 6, 9, 10

**Comment by seongyoo** [comment]
구조체 변수 이름까지 정하기

**Comment by seongyoo** [comment]
책, 영화, 드라마 제목 변수
장르, 내용, 날짜 변수

**Comment by seongyoo** [comment]
book_title, movie_title,drama_title
genre, content, date

**Comment by Kimjisue** [comment]
책 - bo
영화 - mo
드라마 - dr
장르 - kind
내용 - co 
날짜 - date

**Comment by Kimjisue** [comment]
book_t, movie_t, drama_t
genre, content, date

**Comment by Kimjisue** [comment]
이렇게 바꿀까요 ?

**Comment by Kimjisue** [comment]
주제 : 독서 기록장이나 영화 기록 등 날짜와 분야별로 기록할 수 있는 기능

<함수>
1. 메뉴선택창
2. 책, 영화, 드라마를 기록하는 기능
3. 기록한 리스트를 출력하는 기능
4. 기록한 리스트를 수정하는 기능
5. 기록한 리스트를 삭제하는 기능
6. 데이터 파일 저장/읽어오는 기능
7. 책, 영화, 드라마 제목 검색 기능
8. 책, 영화, 드라마 장르 검색 기능
9. 책, 영화, 드라마 날짜 검색 기능
10. 북마크 기능


<구조체>
책, 영화, 드라마 제목 변수(book_t, movie_t, drama_t)
장르, 내용, 날짜 변수(genre, content, date)


<역할분담>
김선교 - 4, 5, 6, 9, 10
김지수 - 1, 2, 3, 7, 8
