### ISSUE TITLE
분야와 장르 

### ISSUE THREAD

**Issue by Kimjisue** [Team18Project/Miniproject#21]
분야와 장르를 하나로 합치는게 어떨까요 ?? 
어떤 분야(책, 영화, 드라마)인지만 입력받는게 좋다고 생각합니다 ~!

**Comment by seongyoo** [comment]
제가 설정한 분야가 책, 영화, 드라마 입니다

**Comment by Kimjisue** [comment]
분야 : 책, 영화, 드라마
장르 : 코미디, 공포, 로맨스 .. 로 하겠습니다
