### ISSUE TITLE
searchRecord 함수

### ISSUE THREAD

**Issue by Kimjisue** [Team18Project/Miniproject#22]
1. searchkind, searchtitle, searchdate 이렇게 검색하는 함수를 여러개 만들까요?
2. searchRecord라는 함수 한개를 만들어서 이 안에서 어떤 내용을 검색할지 입력받게 할까요?

**Comment by seongyoo** [comment]
2번으로 할거면 또다른 함수를 더 만들어야 할까요?

**Comment by seongyoo** [comment]
저는 1번으로 하는게 좋을 것 같습니다!

**Comment by Kimjisue** [comment]
넵 !
