### ISSUE TITLE
wiki 페이지 작성

### ISSUE THREAD

**Issue by seongyoo** [Team18Project/Miniproject#4]

**Comment by seongyoo** [comment]
home 내용 작성

**Comment by Kimjisue** [comment]
<예시>

0. [Home]

1. 서비스
[서비스 상세]
[사용 가이드]
[기술 상세]

2. 디자인
[BI]
[UI/UX]
[리소스]

3.  협업
[개발일지]
[협업 컨벤션]
[프로젝트 참여자]

4. [회고]

Who Are We
박소현 (sohpark)
임지영 (jilim)
정다현 (dachung)

**Comment by seongyoo** [comment]
home 

서비스
서비스 상세
사용 가이드
기술 상세

**Comment by Kimjisue** [comment]
1. 서비스 
- 서비스 상세 
 -> 서비스 개요
 -> 서비스 기획의도
 -> 플로우 차트
 -> 타겟 유저
 -> 기대 효과

- 사용 가이드

- 기술 상세

**Comment by seongyoo** [comment]
home에서는 프로젝트 이름이랑 간략한 설명

**Comment by Kimjisue** [comment]
-

**Comment by seongyoo** [comment]
0. home: 프로젝트 이름, 간략한 설명

1. 서비스

- 서비스 상세
> 서비스 개요
-> 서비스 기획의도
-> 플로우 차트
-> 타겟 유저
-> 기대 효과

- 사용 가이드

- 기술 상세
