### ISSUE TITLE
README.md 만들기 및 역할 분담

### ISSUE THREAD

**Issue by seongyoo** [Team18Project/Miniproject#5]

**Comment by Kimjisue** [comment]
mini project 주제

mini project 에 대한 소개

image(pixabay 등 무료 이미지 활용)

mini project 가 가지고 있는 대략적인 기능 설명

개발환경 및 언어

팀소개 및 팀원이 맡은 역할

**Comment by Kimjisue** [comment]
1. mini project 주제

2. mini project 에 대한 소개

3. mini project 가 가지고 있는 대략적인 기능 설명

4. 개발환경 및 언어

5. 팀소개 및 팀원이 맡은 역할

**Comment by seongyoo** [comment]
1, 2, 4, 5

**Comment by seongyoo** [comment]
3

**Comment by seongyoo** [comment]
Kimjisue: 1, 2, 4, 5
seongyoo: 3
